### ISSUE TITLE
seata只支持druid数据连接池吗，用spring boot 2.0x默认的hikaricp貌似不行啊

### ISSUE THREAD

**Issue by ltlwill** [seata/seata-samples#192]

**Comment by chinaTLJ** [comment]
你是怎么解决的？我的不回滚

**Comment by ltlwill** [comment]
> 
> 
> 你是怎么解决的？我的不回滚

seata目前还有很多问题，我选择用 TX-LCN做分布式事务，效果不错！

**Comment by chinaTLJ** [comment]
> > 你是怎么解决的？我的不回滚
> 
> seata目前还有很多问题，我选择用 TX-LCN做分布式事务，效果不错！

TX-LCN 的服务端依懒哪些东西，是只依懒txlcn-tc和txlcn-txmsg-netty吗，我的不回滚。。

**Comment by ltlwill** [comment]
> 
> 
> > > 你是怎么解决的？我的不回滚
> > 
> > 
> > seata目前还有很多问题，我选择用 TX-LCN做分布式事务，效果不错！
> 
> TX-LCN 的服务端依懒哪些东西，是只依懒txlcn-tc和txlcn-txmsg-netty吗，我的不回滚。。

TX-LCN 实现还是比较简单的，服务端需要 mysql,redis，客户端只需要依赖：txlcn-tc，txlcn-txmsg-netty就行了，我的是完美没问题的，demo在我的github : https://github.com/ltlwill/spring-cloud-projects-alibaba-nacos-Greenwich.RELEASE , 由service-consumer,inventory-service,order-service,account-service 4个服务完成
