### ISSUE TITLE
springboot-dubbo-seata/README.md 有个描述错误

### ISSUE THREAD

**Issue by xkzhangsan** [seata/seata-samples#205]
6. start the normal request
body：

{
    "userId":"1",
    "commodityCode":"P190510529590122",
    "name":"fan",
    "count":2,
    "amount":"100"
}

commodityCode 应该为：C201901140001  和db_seata.sql中的一致，不然运行报错。

**Comment by BeiKeJieDeLiuLangMao** [comment]
@slievrly
You forget to change curl command line, that still uses `P190510529590122`.
