### ISSUE TITLE
demo dubbo miss jackson dependency

### ISSUE THREAD

**Issue by zjinlei** [seata/seata-samples#209]
1.071版本引入了jackson，rm里有jackson依赖。
第一个demo dubbo缺少jackson 依赖，导致undo log生成失败；手动引入jackson依赖可以解决。
2. 日志未输出：手动加log4j.properties会输出。

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.9.1</version>
        </dependency>

**Comment by slievrly** [comment]
![image](https://user-images.githubusercontent.com/8758457/63323451-645f0d00-c358-11e9-9e39-2367cb971d47.png)
