### ISSUE TITLE
是否支持手动触发回滚

### ISSUE THREAD

**Issue by wander-soul** [seata/seata-samples#245]
因业务需求，需要根据情况作出手动触发回滚，通过GlobalTransactionContext.getCurrentOrCreate.rollback()并不能成功直接，spring 事务中有TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();可以实现手动回滚，seata有类型实现吗

**Comment by zjinlei** [comment]
spring回滚的是单机事务，seata是分布式事务，由TM统筹上报TC，你可以抛异常让TM发起回滚。
