### ISSUE TITLE
项目启动不起来，缺少依赖

### ISSUE THREAD

**Issue by cyh03** [seata/seata-samples#249]
1.主要存在以下几个子项目springboot，springcloud-nacos-seata,springcloud-nacos-eureka
2.能否在springboot-mybatis里面添加fegin替换原生的RestTemplate使用

**Comment by xingfudeshi** [comment]
@cyh03 Please do not import root of seata-samples.You need to select a explicit module to import to your IDE.
For your second question,there is a another sample "springcloud-eureka-feign-mybatis-seata",you can refer to it.
