### ISSUE TITLE
Aliyun MySQL information leakage.

### ISSUE THREAD

**Issue by pxchen** [seata/seata-samples#255]
Please check the file.
https://github.com/seata/seata-samples/blob/master/springcloud-jpa-seata/order-service/src/main/resources/application.properties

```properties
spring.datasource.url=jdbc:mysql://rm-****.mysql.rds.aliyuncs.com:3306/fescar?useSSL=false&serverTimezone=UTC
spring.datasource.username=w**p
spring.datasource.password=W****3
```

The Aliyun MySQL information is not removed.

**Comment by slievrly** [comment]
@pxchen this db is open for test.
