### ISSUE TITLE
No provider available for the service

### ISSUE THREAD

**Issue by YangXueJun** [seata/seata-samples#276]
项目如下
![image](https://user-images.githubusercontent.com/11888152/69853620-55c2b300-12c2-11ea-91cc-288139f38dd9.png)

Start after service consumers start first, the service provider, will lead to the service consumer can not find the service provider, will appear the following error.If the service provider to start the first would not have this problem.
服务消费者先启动，服务提供者后启动，就会导致服务消费者找不到服务提供者，就会出现如下错误。
如果服务提供者先启动则没有这个问题。

```
Failed to invoke the method test in the service io.seata.samples.sca.common.dubbo.api.TestService. No provider available for the service io.seata.samples.sca.common.dubbo.api.TestService from registry 106.14.1.178:9090 on the consumer 10.70.12.171 using the dubbo version 2.7.3. Please check if the providers have been started and registered.
```

**Comment by YangXueJun** [comment]
这是一个bug，后面b版本解决了
![image](https://user-images.githubusercontent.com/11888152/69854415-0da49000-12c4-11ea-80d3-17d8fbccc5d4.png)

**Comment by slievrly** [comment]
@YangXueJun great found.
