### ISSUE TITLE
springboot-dubbo-seata module 无法启动

### ISSUE THREAD

**Issue by ray9527** [seata/seata-samples#279]
按照readme里走的，但是在启动module项目的时候无法启动，控制台信息：
![image](https://user-images.githubusercontent.com/32827610/70030381-13f87c00-15e4-11ea-9966-72be1b42812b.png)

nacos：
![image](https://user-images.githubusercontent.com/32827610/70030243-c24ff180-15e3-11ea-8fb9-8aa70f0576e5.png)

seata:
![image](https://user-images.githubusercontent.com/32827610/70030432-2f638700-15e4-11ea-9c24-284da274c2fe.png)

数据库链接都看过了没有问题，sql脚本也执行了的

**Comment by noenif** [comment]
老哥如何解决的
