### ISSUE TITLE
springcloud-nacos-seata整合，报错：i.s.c.r.netty.NettyClientChannelManager  : no available server to connect.

### ISSUE THREAD

**Issue by LuciferZK** [seata/seata-samples#282]
控制台一直报错：

![微信截图_20191210165049](https://user-images.githubusercontent.com/38940745/70513845-60f0cb00-1b6d-11ea-9982-1e1e57ae0991.png)

**1、application.properties**
- order-server:
   spring.cloud.alibaba.seata.tx-service-group=order-service-group

- storage-service：
  spring.cloud.alibaba.seata.tx-service-group=storage-service-group

2**、nacos配置管理：**
![微信截图_20191210164824](https://user-images.githubusercontent.com/38940745/70513611-f2137200-1b6c-11ea-9034-17ffdefae3da.png)

**3、nacos-config.txt**
![微信截图_20191210164938](https://user-images.githubusercontent.com/38940745/70513732-2424d400-1b6d-11ea-913b-26bd27916a7f.png)

**Comment by LuciferZK** [comment]
**环境：** seata-server-0.9.0; nacos-server-1.1.4； **pom.xml** ：seata-all 0.9.0

**Comment by Tenvie** [comment]
请问你是怎么解决的

**Comment by dongwenting** [comment]
我也是一直报错，唉，seata 1.1.0一堆bug，退回到0.9.0还是一堆bug
