### ISSUE TITLE
no available service 'default' found, please make sure registry config correct

### ISSUE THREAD

**Issue by zhi-leaf** [seata/seata-samples#297]
springcloud-eureka-seata目录下，启动好eureka，再启动其他工程，不停的刷error错误。
ERROR 7020 --- [imeoutChecker_1] i.s.c.r.netty.NettyClientChannelManager  : no available service 'default' found, please make sure registry config correct

**Comment by TonyHuiHUI** [comment]
我再springcloud-nacos-seata也出现同样的问题。请问解决了么？

**Comment by zhi-leaf** [comment]
解决了，seta有一个服务端必须先启动，下载地址：https://github.com/seata/seata/releases/download/v1.2.0/seata-server-1.2.0.zip

**Comment by TonyHuiHUI** [comment]
> 解决了，seta有一个服务端必须先启动，下载地址：https://github.com/seata/seata/releases/download/v1.2.0/seata-server-1.2.0.zip

感谢回复。我使用的是docker镜像启动的seata-server，然后在启动的示例中的order服务。没明白错在哪。不知道你是否了解。

**Comment by zhi-leaf** [comment]
https://github.com/zhi-leaf/seata-demo，临时给你公开一下，这是我复制官方示例做的demo，用于研究。昨天还能跑的，seta服务端你用1.1版本，因为file.conf里面的service我配置的是127.0.0.1，你就在自己电脑跑

**Comment by TonyHuiHUI** [comment]
> [https://github.com/zhi-leaf/seata-demo，临时给你公开一下，这是我复制官方示例做的demo，用于研究。昨天还能跑的，seta服务端你用1.1版本，因为file.conf里面的service我配置的是127.0.0.1，你就在自己电脑跑](https://github.com/zhi-leaf/seata-demo%EF%BC%8C%E4%B8%B4%E6%97%B6%E7%BB%99%E4%BD%A0%E5%85%AC%E5%BC%80%E4%B8%80%E4%B8%8B%EF%BC%8C%E8%BF%99%E6%98%AF%E6%88%91%E5%A4%8D%E5%88%B6%E5%AE%98%E6%96%B9%E7%A4%BA%E4%BE%8B%E5%81%9A%E7%9A%84demo%EF%BC%8C%E7%94%A8%E4%BA%8E%E7%A0%94%E7%A9%B6%E3%80%82%E6%98%A8%E5%A4%A9%E8%BF%98%E8%83%BD%E8%B7%91%E7%9A%84%EF%BC%8Cseta%E6%9C%8D%E5%8A%A1%E7%AB%AF%E4%BD%A0%E7%94%A81.1%E7%89%88%E6%9C%AC%EF%BC%8C%E5%9B%A0%E4%B8%BAfile.conf%E9%87%8C%E9%9D%A2%E7%9A%84service%E6%88%91%E9%85%8D%E7%BD%AE%E7%9A%84%E6%98%AF127.0.0.1%EF%BC%8C%E4%BD%A0%E5%B0%B1%E5%9C%A8%E8%87%AA%E5%B7%B1%E7%94%B5%E8%84%91%E8%B7%91)

感谢感谢。我看了下你的demo，你使用的注册中心是file，在这个模式下可以找到本地的TC。在springCloud-seata-nacos的示例中用的是nacos做注册中心。不知道什么问题导致无法发现default这个TC，所以才不听报这个错。

**Comment by zhi-leaf** [comment]
那你的问题我也帮不了啦，nacos不是我研究的重点，所有不关注，仓库的代码既然没用，我就关啦。

**Comment by TonyHuiHUI** [comment]
> 那你的问题我也帮不了啦，nacos不是我研究的重点，所有不关注，仓库的代码既然没用，我就关啦。

好的，还是十分感谢。我继续研究研究

**Comment by caozk929** [comment]
![image](https://user-images.githubusercontent.com/11494156/89606654-1ada3b80-d8a3-11ea-8fb2-f2ed90bd4813.png)
看源码，seata server 注册到nacos的服务名必须是“serverAddr”，这也太挫了吧
