### ISSUE TITLE
demo的db连接你们都提交…

### ISSUE THREAD

**Issue by ChoviWu** [seata/seata-samples#327]
刚拉下来这个项目，master上的springcloud-eureka-seata 连接阿里云的db的都提交了，具体位置springcloud-eureka-seata/account/src/main/resources/application.properties等等…

**Comment by Garlichead** [comment]
这个大众都没提交权限了 只有参与者吧 我试了下自己的分支都无法push 只能提交到本地

**Comment by ChoviWu** [comment]
demo工程尽量不要掺杂commiter或者contributer的个人项目环境，希望你们合的时候review下代码
