### ISSUE TITLE
springcloud-jpa-seata : no available service 'null' found, please make sure registry config correct

### ISSUE THREAD

**Issue by xpzsoft-maker** [seata/seata-samples#354]
service {
  #transaction service group mapping
  vgroup_mapping = "account-service" # 报错 no available service 'null' found, please make sure registry config correct
 vgroupMapping = "account-service" # 报错 no available service 'null' found, please make sure registry config correct
  #only support when registry.type=file, please don't set multiple addresses
  default.grouplist = "127.0.0.1:8091"
  #degrade, current not support
  enableDegrade = false
  #disable seata
  disableGlobalTransaction = false
}

在那里能看到file.config的详细配置说明？

**Comment by xpzsoft-maker** [comment]
已解决

**Comment by arraycto** [comment]
大佬，请问您怎么解决的，报错
``no available service 'null' found, please make sure registry config correct``

**Comment by arraycto** [comment]
@xpzsoft-maker
