### ISSUE TITLE
seata-server 部署在远程的主机上，Spring cloud 服务总是显示连接不上服务，怎么处理呢？

### ISSUE THREAD

**Issue by Suomea** [seata/seata-samples#355]
我的 seata-server 部署在 ip 为 a.a.a.a 的机器上，本地启动后一致报错，如下：
![image](https://user-images.githubusercontent.com/26758537/84727543-daa4be00-afc1-11ea-8848-aa4604d9d02f.png)

和我的 a.a.a.a 的机器没有连接上，怎么配置处理呢？

**Comment by Suomea** [comment]
什么都没动，本地启动 seata server，然后 Spring Cloud 的服务就能正常启动了。

**Comment by xpzsoft-maker** [comment]
1，启动server时，设置一下host
sh seata-server.sh -h 127.0.0.1 -m file
2，配置server/conf 下的file.conf文件
3， 配置demo下的file.conf和application.properties

**Comment by xpzsoft-maker** [comment]
这个demo项目好像维护的不是很好啊，文档写的也不好，坑多，我昨天也是花了半天才把springcloud-jpa-sample成功跑出来。

**Comment by Suomea** [comment]
> 1，启动server时，设置一下host
> sh seata-server.sh -h a.a.a.a -m file
> 2，配置server/conf 下的file.conf文件
> 3， 配置demo下的file.conf和application.properties

这个 demo 中的配置文件如何配置 a.a.a.a 的地址呢？

**Comment by xpzsoft-maker** [comment]
在demo的file.conf中配置，file.conf问价在resources目录下
service {
  #transaction service group mapping
  vgroup_mapping = "account-service"
  #only support when registry.type=file, please don't set multiple addresses
  default.grouplist = "127.0.0.1:8091" #这里配置为a.a.a.a:port
  #degrade, current not support
  enableDegrade = false
  #disable seata
  disableGlobalTransaction = false
}

**Comment by Suomea** [comment]
> 在demo的file.conf中配置，file.conf文件在resources目录下
> service {
> #transaction service group mapping
> vgroup_mapping = "account-service"
> #only support when registry.type=file, please don't set multiple addresses
> default.grouplist = "127.0.0.1:8091" #这里配置为a.a.a.a:port
> #degrade, current not support
> enableDegrade = false
> #disable seata
> disableGlobalTransaction = false
> }

我的版本是 1.2.0，这样我试了也不行。最后在钉钉群里有大佬回复解决了，这样配置 server 的地址：
![image](https://user-images.githubusercontent.com/26758537/84865287-888b9780-b0aa-11ea-860b-542b964ef842.png)
