### ISSUE TITLE
seata集成nacos启动问题，globalTransactionScanner config type can not be null

### ISSUE THREAD

**Issue by jiachen-xu95** [seata/seata-samples#394]
Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: config type can not be null

**Comment by Kevin-Karl-Wang** [comment]
你是怎么解决的?

**Comment by cazcen** [comment]
Error creating bean with name 'globalTransactionScanner' defined in class path resource [com/alibaba/cloud/seata/GlobalTransactionAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.seata.spring.annotation.GlobalTransactionScanner]: Factory method 'globalTransactionScanner' threw exception; nested exception is io.seata.common.exception.NotSupportYetException: config type can not be null

**Comment by cazcen** [comment]
怎么解决的？

**Comment by zhilong-12138** [comment]
解决了吗?xdm

**Comment by liuzhen520** [comment]
我也是遇到这个问题，有大神直到怎么解决么

**Comment by jiachen-xu95** [comment]
时间有点久远，可以参考我自己demo中的配置文件，https://github.com/jiachen-xu95/seata/tree/main/seata-saga
