### ISSUE TITLE
 can not get cluster name in registry config 'service.vgroupMapping.storage_service_group', please make sure registry config correct

### ISSUE THREAD

**Issue by freshgeek** [seata/seata-samples#411]
version:
seata:1.4.0
nacos:1.4.0
spring-boot:2.2.2.RELEASE
spring-cloud:Hoxton.SR1

```text

2020-12-14 16:18:26.600 ERROR [seata-storage-service,,,] 444 --- [           main] i.s.c.r.netty.NettyClientChannelManager  : can not get cluster name in registry config 'service.vgroupMapping.storage_service_group', please make sure registry config correct

```

- [https://github.com/seata/seata-samples/tree/master/springcloud-nacos-seata ](https://github.com/seata/seata-samples/tree/master/springcloud-nacos-seata )

![image](https://user-images.githubusercontent.com/20513615/102057266-a43ce400-3e28-11eb-8f1d-decaa0c0e71c.png)
 
In the high version of Seata, if you should use the `service.vgroupMapping.order-service-group=default`, an underline will cause the service not to be found
 
Hope to be able to describe the exception clearly, without users to guess 

and ` service.vgroupMapping.order_service_group=default ` also error

**Comment by 804434940** [comment]
请问您解决了么 我按照这个方式还是报这个错

**Comment by huxipi** [comment]
版本1.4.1，报同样的错误：
i.s.c.r.netty.NettyClientChannelManager  : can not get cluster name in registry config 'service.vgroupMapping.seata-account-service-fescar-service-group', please make sure registry config correct

尝试各种方法，未解决

**Comment by 844704781** [comment]
未解决

**Comment by HelloWorldHelloPKU** [comment]
> 版本1.4.1，报同样的错误：
> i.s.c.r.netty.NettyClientChannelManager : can not get cluster name in registry config 'service.vgroupMapping.seata-account-service-fescar-service-group', please make sure registry config correct
> 
> 尝试各种方法，未解决
在application.properties中添加
spring.cloud.alibaba.seata.tx-service-group=my_test_tx_group
注意my_test_tx_group是file.conf中service中配置的vgroupMapping.**my_test_tx_group** = "default"

**Comment by pangchun** [comment]
不妨看看我的回答：（已解决）

版本1.4.2，配置中心为nacos
同样是控制台不停打印此错误，如下：
![image](https://user-images.githubusercontent.com/57040675/134299533-a4346abc-5207-4dc8-8c73-ed12abfdf7c0.png)

思路：仍然是事务分组名的问题；

解决办法：集成至项目时我们一般都会修改service.vgroupMapping.my_test_tx_group=default中的my_test_tx_group，然后就容易碰到上述问题，解决办法分两步：
1、yml中要配置事务分组名：
比如我的配置修改为service.vgroupMapping.seata-storage-service=default，那么yml中要配置tx-service-group: seata-storage-service；
2、nacos中需要增加一个dataId为service.vgroupMapping.seata-storage-service，内容为default的配置，如下：（一定要注意的是seata在nacos上的所有配置可以通过seata提供的脚本一键导入）
![image](https://user-images.githubusercontent.com/57040675/134300695-60ad1893-7e93-4491-8692-d845d0a58a69.png)
这样一来，问题便得到了解决。

至于为什么需要第二步，请继续看：
1、报错时，debug进入此方法，再进入lookup方法查看：
![image](https://user-images.githubusercontent.com/57040675/134301445-f2ce4641-bc06-4ed7-8f0c-0a329a93c67c.png)

2、沿着空值一直找到最后：
![image](https://user-images.githubusercontent.com/57040675/134301562-f3b4a70d-a814-4f26-883c-e36b0eca9fd5.png)
![image](https://user-images.githubusercontent.com/57040675/134301807-6f642efd-6488-4133-b3c5-4b5544e4cfe5.png)
发现最终从nacos获取配置时是从这个dataId获取的，而我们的配置中心没有此dataId的配置，再看到下图中的service.vgroupMapping.my_test_tx_group示例，添加一个service.vgroupMapping.seata-storage-service配置即可。
![image](https://user-images.githubusercontent.com/57040675/134302221-3eb48e46-b70f-4140-a281-ab2520103ffe.png)

**Comment by hoxiete** [comment]
@pangchun  感谢你的回答，我也是dataId没有指定service.vgroupMapping，问题是seata1.4.2已经支持以dataId = "seata-server.properties"形式读取键值，可能是client的seata版本低了

**Comment by pangchun** [comment]
> 
我觉得挺好用的，不知道你是指哪方面难用

**Comment by hcqbuqingzhen** [comment]
> 
抱歉是我口嗨了,大致就是配置方面吧.就像这里出现的问题.我也是通过您这条回答解决的.虽然解决了,还是觉得官方文档没有说清楚吧.

**Comment by yearnxiao** [comment]
> > 
> 
> 抱歉是我口嗨了，大致就是配置方面吧。就像这里出现的问题。我也是通过您的这条回答解决的。虽然解决了，还是觉得官方文档没有说清楚吧。

说实话seata配置这块的官方文档和demo确实不够清晰，很多资深开发都搞不明白
