### ISSUE TITLE
wiki 文档问题

### ISSUE THREAD

**Issue by luoxn28** [seata/seata-samples#417]
目前最新的 seata undolog 包含context 字段，但是 wiki上文档还未更新，会导致按照 wiki 上操作的话启动seata 示例工程报错：
- [How-to-use-Seata-to-ensure-consistency-between-Dubbo-Microservices](https://github.com/seata/seata-samples/wiki/How-to-use-Seata-to-ensure-consistency-between-Dubbo-Microservices)
- [如何使用Seata保证Dubbo微服务间的一致性](https://github.com/seata/seata-samples/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Seata%E4%BF%9D%E8%AF%81Dubbo%E5%BE%AE%E6%9C%8D%E5%8A%A1%E9%97%B4%E7%9A%84%E4%B8%80%E8%87%B4%E6%80%A7)

空了麻烦更新下，最新版 undolog sql 如下：
```sql
-- 注意此处0.3.0+ 增加唯一索引 ux_undo_log
DROP TABLE IF EXISTS `undo_log`;
CREATE TABLE `undo_log` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `branch_id` bigint(20) NOT NULL,
  `xid` varchar(100) NOT NULL,
  `context` varchar(128) NOT NULL,
  `rollback_info` longblob NOT NULL,
  `log_status` int(11) NOT NULL,
  `log_created` datetime NOT NULL,
  `log_modified` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_undo_log` (`xid`,`branch_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```

**Comment by slievrly** [comment]
@luoxn28 thanks，already fixed.
