### ISSUE TITLE
ApplicationKeeper.java 的等待命令 wait() 编写有误

### ISSUE THREAD

**Issue by bigcai** [seata/seata-samples#422]
https://github.com/seata/seata-samples/blob/master/dubbo/src/main/java/io/seata/samples/dubbo/ApplicationKeeper.java

这里用 ReentrantLock 的 condition 条件变量把主线程挂起，等优雅关机后才唤醒主线程。

LOCK 是 ReentrantLock  实例， STOP 是 LOCK 的 Condition 变量。
故
  LOCK.wait();  应该 改为  STOP.wait();

   /**
     * Keep.
     */
    public void keep() {
        synchronized (LOCK) {
            try {
                LOGGER.info("Application is keep running ... ");
                LOCK.wait();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

**Comment by slievrly** [comment]
@bigcai pls submit a PR.

**Comment by ZJRui** [comment]
> 

hello，问个问题哈，
第一，首先我看到了你 针对这个问题 提交的改进的代码  https://github.com/seata/seata-samples/pull/423


第二，关于这个代码
https://github.com/seata/seata-samples/blob/4e4a579aa7d7866b1a786f5d347c2b333e1bb0ec/ha/src/main/java/io/seata/samples/nacos/ApplicationKeeper.java#L72


为啥还要创建一个conditon？ 想挂起当前的线程，直接用ReentrantLock对象上的从Object 继承来的wait方法不久可以了么？
ShoutdownHook中也没啥 需要使用ReentrantLock和Conditon的必要性吧？
