### ISSUE TITLE
1.4.1 版本 nacos 配置会和工程已有的 group 冲突吗？

### ISSUE THREAD

**Issue by ZhangX-Byte** [seata/seata-samples#424]
seata nacos 所在组为 SEATA_GROUP,我工程配置所在组为 DEFUALT_GROUP。

client registry.con 内容为：

registry {
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "localhost"
    namespace = "dev"
    cluster = "default"
    username = "nacos"
    password = "nacos"
  }
}

config {
  type = "nacos"

  nacos {
    serverAddr = "localhost"
    namespace = "dev"
    group = "SEATA_GROUP"
    username = "nacos"
    password = "nacos"
  }
}

application.properties 配置为：

spring.profiles.active=dev
logging.config=classpath:logback-${spring.profiles.active}.xml
spring.application.name=order
seata.tx-service-group=order-server-tx-group

bootstrap-dev.properties 配置为：

spring.cloud.nacos.config.server-addr=localhost:8848
spring.cloud.nacos.config.namespace=dev
spring.cloud.nacos.config.file-extension=yaml
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.discovery.namespace=dev
spring.cloud.nacos.discovery.server-addr=localhost:8848

启动服务，得到错误：
can not get cluster name in registry config 'service.vgroupMapping.order-server-tx-group', please make sure registry config correct

当发送请求时，得到错误：

10:11:38.329 INFO [,] i.s.t.TransactionManagerHolder[L:40] - TransactionManager Singleton io.seata.tm.DefaultTransactionManager@7174d5b
10:11:38.362 ERROR[,] c.a.s.c.GlobalExceptionHandler[L:33] - No available service
10:11:38.362 ERROR[,] c.a.s.c.GlobalExceptionHandler[L:44] - stackError[系统错误！io.seata.common.exception.FrameworkException: ]

请问我配置哪里有问题？

**Comment by HyberLinker** [comment]
> seata nacos 所在组为 SEATA_GROUP,我工程配置所在组为 DEFUALT_GROUP。
> 
> client registry.con 内容为：
> 
> registry {
> type = "nacos"
> 
> nacos {
> application = "seata-server"
> serverAddr = "localhost"
> namespace = "dev"
> cluster = "default"
> username = "nacos"
> password = "nacos"
> }
> }
> 
> config {
> type = "nacos"
> 
> nacos {
> serverAddr = "localhost"
> namespace = "dev"
> group = "SEATA_GROUP"
> username = "nacos"
> password = "nacos"
> }
> }
> 
> application.properties 配置为：
> 
> spring.profiles.active=dev
> logging.config=classpath:logback-${spring.profiles.active}.xml
> spring.application.name=order
> seata.tx-service-group=order-server-tx-group
> 
> bootstrap-dev.properties 配置为：
> 
> spring.cloud.nacos.config.server-addr=localhost:8848
> spring.cloud.nacos.config.namespace=dev
> spring.cloud.nacos.config.file-extension=yaml
> spring.cloud.nacos.config.group=DEFAULT_GROUP
> spring.cloud.nacos.discovery.namespace=dev
> spring.cloud.nacos.discovery.server-addr=localhost:8848
> 
> 启动服务，得到错误：
> can not get cluster name in registry config 'service.vgroupMapping.order-server-tx-group', please make sure registry config correct
> 
> 当发送请求时，得到错误：
> 
> 10:11:38.329 INFO [,] i.s.t.TransactionManagerHolder[L:40] - TransactionManager Singleton io.seata.tm.DefaultTransactionManager@7174d5b
> 10:11:38.362 ERROR[,] c.a.s.c.GlobalExceptionHandler[L:33] - No available service
> 10:11:38.362 ERROR[,] c.a.s.c.GlobalExceptionHandler[L:44] - stackError[系统错误！io.seata.common.exception.FrameworkException: ]
> 
> 请问我配置哪里有问题？

@ZhangX-Byte 请问你是怎么解决这个问题的？按照readme配置，现在依然报错can not get cluster name in registry config

**Comment by ZhangX-Byte** [comment]
@HyberLinker 

bootstrap.properties 配置中添加：

``` 
seata.tx-service-group=app-server-tx-group
seata.config.type=nacos
seata.config.nacos.server-addr=127.0.0.1:8848
seata.config.nacos.namespace=3a2aea46-07c6-4e21-9a1e-8946cde9e2b3
seata.config.nacos.group=SEATA_GROUP
```

参考这篇博客 https://www.cnblogs.com/Zhang-Xiang/p/14430618.html
