### ISSUE TITLE
Error preparing statement.  Cause: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder

### ISSUE THREAD

**Issue by wwkin** [seata/seata-samples#426]
在mybatis查询数据时出现这个错误：
**Error preparing statement.  Cause: io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder**

**Comment by srg1556** [comment]
你好，楼主，请问问题解决了吗？我遇到和你一样的问题

**Comment by niaoshuai** [comment]
切换成 最新版本的 seata server 就能搞定了

**Comment by shanjia-sdu** [comment]
> 切换成 最新版本的 seata server 就能搞定了

我用的1.4.2，也报这个错，而且捕捉不到异常堆栈信息。

io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.sqlparser.druid.SQLOperateRecognizerHolder
