### ISSUE TITLE
nested exception is java.lang.NoSuchMethodError: org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.setClassValuesAsString(Z)V

### ISSUE THREAD

**Issue by twhuo** [seata/seata-samples#456]
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'referenceAnnotationBeanPostProcessor': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.setClassValuesAsString(Z)V

**Comment by Dejia2017** [comment]
> Please check the dependency named "com.alibaba.spring:spring-context-support" whose version should be 1.0.11 and above.
> 
> `<dependency>` `<groupId>com.alibaba.spring</groupId>` `<artifactId>spring-context-support</artifactId>` `<version>1.0.11</version>` `</dependency>`

useful

**Comment by tankilo** [comment]
> Please check the dependency named "com.alibaba.spring:spring-context-support" whose version should be 1.0.11 and above.
> 
> `<dependency>` `<groupId>com.alibaba.spring</groupId>` `<artifactId>spring-context-support</artifactId>` `<version>1.0.11</version>` `</dependency>`

Why not post an PR to fix it?  It seems that this project is no longer actively maintained. This problem still happened today.

**Comment by niaoshuai** [comment]
已经有PR修复了 https://github.com/seata/seata-samples/pull/481
