### ISSUE TITLE
can not get cluster name in registry config 

### ISSUE THREAD

**Issue by Angle-bo** [seata/seata-samples#461]
nacos-2.0.2
seata-1.4.2 
can not get cluster name in registry config

seataServer.properties配置文件
service.vgroupMapping.hsmanager_cloud_seata_tx_group=default

项目配置
seata:  
    tx-service-group: hsmanager_cloud_seata_tx_group
    service:
    vgroup-mapping:
      hsmanager_cloud_seata_tx_group: default
  
还有哪里需要配置？

**Comment by slievrly** [comment]
@Angle-bo Check whether Seata config.type uses a third-party configuration center.

**Comment by Surrin1999** [comment]
> @Angle-bo Check whether Seata config.type uses a third-party configuration center.

Seata 1.5.x整合SpringBoot时就是因为没有设置seata.config.type和seata.registry.type为nacos用了默认的file一直报错。。不得不说这报错提示也太没用了
