### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by chenming7583** [seata/seata-samples#58]
![image](https://user-images.githubusercontent.com/5953863/54426598-3cd59a00-4753-11e9-86ed-0e4af36aa4e3.png)
这应该是个内部版本吧

**Comment by slievrly** [comment]
@chenming7583 tcc not released

**Comment by chenming7583** [comment]
> @chenming7583 tcc not released

噢 那我本地编译一下tcc

**Comment by slievrly** [comment]
已修复
