### ISSUE TITLE
qos-server 端口冲突

### ISSUE THREAD

**Issue by 3EDCKenneth** [seata/seata-samples#62]
采用springboot demo，  
按照
enable=true
port=33333
acceptForeignIp=false
修改不起作用, 启动单个项目没问题， 多个端口冲突

**Comment by slievrly** [comment]
是说端口冲突吗？

**Comment by 3EDCKenneth** [comment]
@slievrly  是的， 本地启动2个，端口22222无法通过参数配置修改

**Comment by wendal** [comment]
把dubbo的qos关掉就行了
